[package]
name = "move-bytecode-to-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
move-package.workspace = true
move-binary-format.workspace = true

walrus = "0.23"
wasmprinter = "0.227"
wasmparser = "0.227"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
