[package]
name = "example"
edition = "2024"

[dependencies]
StylusFramework = { local = "../stylus-framework/" }
Erc20Call = { local = "../erc20call/" }
Erc721Utils = { local = "../erc721Utils/" }

[addresses]
hello_world = "0x0"
