[package]
name = "example"
edition = "2024"
flavor = "core"

[dependencies]
Erc20Call = { git = "https://github.com/rather-labs/move-stylus/", subdir = "move-packages/erc20call", rev = "main" }
Erc721Utils = { git = "https://github.com/rather-labs/move-stylus/", subdir = "move-packages/erc721Utils", rev = "main" }

[addresses]
hello_world = "0x0"
