[package]
name = "move-parse-special-attributes"
version = "0.1.0"
edition = "2024"

[dependencies]
move-compiler.workspace = true
move-ir-types.workspace = true
move-symbol-pool.workspace = true
thiserror.workspace = true
