[package]
name = "move-evm-abi-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
move-compiler.workspace = true
move-parse-special-attributes.workspace = true
move-bytecode-to-wasm.workspace = true
